### ISSUE TITLE
again, more of a question

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#33]
Sunkyu: I still don't know how to save the link for wikipedia or baidu. It worked well in TGAZ or DILA. Just a question:if I want multiple external authority, should I create another property or can I save more than one link on the same property?

**Comment by rsimon** [comment]
We should also discuss this. At the moment, you would need to create multiple fields if you want to add multiple identifiers. But I was thinking that some kind of a "allow multiple" option would be useful as a general aspect for every metadata property. This way, you'd e.g. get a Plus button underneath a field, and can add multiple values. This would work for the example above. But I could also imagine it to be useful for things like adding an arbitrary number of alternative names to an entity, etc.

**Comment by rsimon** [comment]
Closing this in favor of issue #47, which is specifically about multi-value fields.
