### ISSUE TITLE
add image note in the tool tab (where the buttons are) does not exist eny more?

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#36]
Hi
we saw that this was removed. Can you confirm this and why was it removed?
best
I

**Comment by rsimon** [comment]
The image note was replaced by the image metadata. IMO it doesn't make sense to have a hard-wired notes field AND freely defined metadata. If you want to record notes on a specific image, you would simply add a "Notes" fields (type text, multi-line) to your image metadata schema.

**Comment by StoIva** [comment]
great. thank you
