### ISSUE TITLE
problem with options 

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#42]
I went to the data model view to edit the properties; and then I can see that option is added to the existing options. But still I cannot choose that option.  I can see that plain and stripe are added now but still cannot choose them. If I click nothing changes. 
![Screenshot (471)](https://github.com/rsimon/immarkus/assets/128056738/0affcd92-b797-4195-a5da-e5a1c2b8505c)

**Comment by rsimon** [comment]
Can you see an error message in the F12-console?

**Comment by rsimon** [comment]
Like with issue #41, I cannot reproduce this. Do you want to jump on a quick screenshare call?

**Comment by StoIva** [comment]
Hi. Sorry, I could not answer. I will see with Sunkyu, maybe I should try reproducing the issue myself and get back to you
