### ISSUE TITLE
switching images

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#43]
When I am annotating two images together sometimes after saving one annotation and click Move, the images switch

**Comment by StoIva** [comment]
![Screenshot (472)](https://github.com/rsimon/immarkus/assets/128056738/37a155f1-65c8-440e-aa81-cf43f25ca0e7)

This issue only occurs when the images are numbered reverse (like 53 on the right and 52 on the left and it kept switching to 53 on the left and 52 on the right)--which is very common in Chinese books as they read from right to left.

**Comment by rsimon** [comment]
Ah - I see what's going on. The window layout is using state when other parts of the UI change... It will take a bit, but it's fixable!

**Comment by rsimon** [comment]
Hi @StoIva, this is now fixed on the test instance at [immarkus.rainersimon.io](https://immarkus.rainersimon.io).

**Comment by StoIva** [comment]
great. thank you
