### ISSUE TITLE
Export Metadata

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#50]
One tester had an issue with this: Chinese characters still unreadable, I have had this problem with excel/csv before, other programs can still read and convert

i am testing today and i will see if i can replicate

**Comment by rsimon** [comment]
Thanks! Can you provide more information? Where are they unreadable? Is this about importing files with Chinese characters in filenames? Or when opening an exported file in Excel? (Or somewhere else?)

**Comment by StoIva** [comment]
it is in the file itself. if the "location" is filled out in chinese characters it shows nonsense (e.g.+-*/) in the csv file. that happens in csv files if you input chinese ch., and usually the program can retrieve this info. however if we work with the csv itself it will i think still show nonsense

**Comment by rsimon** [comment]
Can you forward an affected file? It should come out of IMMARKUS as a UTF-8-encoded file. If software (like Excel) can correctly read the characters, it sounds as if that works correctly. When you say the "file itself", which software are you using to view it? (Some tools - like the Windows TextEdit viewer - have problems with UTF-8 encoded content. I.e. it might actually be a problem of the viewer, not the file.)

**Comment by StoIva** [comment]
[folder_metadata.csv](https://github.com/rsimon/immarkus/files/14417967/folder_metadata.csv)
[image_metadata.csv](https://github.com/rsimon/immarkus/files/14417968/image_metadata.csv)

**Comment by StoIva** [comment]
i did the export and had the same issue. these are my metadata exports

**Comment by rsimon** [comment]
Ok, no sorry - it looks like the CSV is entirely correct. It must be the software you are using to view it, and which is not able to correctly view UTF-8 files/Chinese characters. (Can you confirm which software this is?)

I'm attaching a few screenshots I just recorded when opening your `folder_metadata.csv` above in different tools, all of which seemed to display it correctly.

__Numbers:__ (a simple Mac Excel clone & default tool for CSVs)

<img width="1397" alt="Bildschirmfoto 2024-02-27 um 11 22 32" src="https://github.com/rsimon/immarkus/assets/470971/aa0daced-b533-4c11-8ebf-f9eff481d0cd">

__TextEdit:__ (a simple text editor)

<img width="758" alt="Bildschirmfoto 2024-02-27 um 11 23 18" src="https://github.com/rsimon/immarkus/assets/470971/867400a9-135f-4ddd-ba6c-fb92fdb902ca">

__Google Sheets:__

<img width="1075" alt="Bildschirmfoto 2024-02-27 um 11 28 22" src="https://github.com/rsimon/immarkus/assets/470971/233e3dfa-7c7e-4094-a45f-b86d803424fd">

**Comment by StoIva** [comment]
it is MS Excel for both me and Meret. it is then indeed a software issue (since it works in notepad). maybe we should put that in the guidelines? or an FAQ?

**Comment by rsimon** [comment]
Ah, got it. Yes, Excel has known issues with pretty much anything that's not English ;-) I agree this would be good to include into the guidelines. The trick has always been to __not__ open the CSV file with Excel directly, but instead use Excel's data import feature, which works better. Here's one article. But if you google something like "open utf-8 csv file in excel" you will see that - unfortunately - it's a very common problem :-(

https://answers.microsoft.com/en-us/msoffice/forum/all/how-to-open-utf-8-csv-file-in-excel-without-mis/1eb15700-d235-441e-8b99-db10fafff3c2
