### ISSUE TITLE
metadata: fill out and save folders schemas

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#51]
whenever I save and reopen the folder metadata, the sections ‘Date created' (number property), Location (geo coordinate) and Length (measurement) are blank again, however they still appear in the json file

**Comment by rsimon** [comment]
Can you share a folder where this is happening? (Or attach the `_immarkus.folder.meta.json` file.) I couldn't reproduce this on my end. (Added a number + geolocation property, filled the values for a folder and saved. The values were both in the JSON file, as well as in the sidebar when I closed and re-opened.)

**Comment by rsimon** [comment]
Duplicate to #65
