### ISSUE TITLE
Question on json file

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#52]
The json file on image level now includes a context section, recording data on who and when is working on the file. The creator field is blank, should we imput something manually?

**Comment by rsimon** [comment]
The `creator` field has always been there. It's part of the Web Annotation standard, but not mandatory. 

I assume it would be best to remove it? (Normally, this would include a username. However since IMMARKUS doesn't have a login/user management, the field isn't actually applicable.)
