### ISSUE TITLE
did not test this because i am scared to do it :) but it should be a priority

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#55]
Does the platform still show a blank screen if you click on the annotation when the entity class was deleted? and then you cannot delete the annotation, it just goes blank every time

**Comment by rsimon** [comment]
No this should be fine now. If you delete an entity class, all the annotations in the system are updated. This means the annotation would still be there, but no longer be tagged with that class.

**Comment by StoIva** [comment]
tested and works fine. thank you
