### ISSUE TITLE
Carry undo/redo history over to the new Annotator when adding/removing images to workspace

### ISSUE THREAD

**Issue by rsimon** [rsimon/immarkus#56]
The undo/redo stack is tied to the Annotator instance. If a second image is added to a workspace that only has a single image, the existing image will be unmounted, and a new window (with a new Annotator) will be mounted. This means that the previous undo/redo history is lost. We should add functionality for carrying over the history of the old (unmounted) Annotator to the new Annotator.

**Comment by StoIva** [comment]
one question about this: are we planning to make undo/redo possible once the image is closed and reopened? this is currently not possible, but would be good to know how excatly the two buttons work so we can put that in the instructions

**Comment by rsimon** [comment]
I'm afraid it's not possible to undo a step that you made before closing the image (or closing IMMARKUS). Once you close the image view, the history is gone. If we wanted change this, we'd need to save a full version history record with every image, which would be a bigger change.

Carrying over the history when adding a new image to the workspace is less of a problem, because then the application is still in the same "session", as it were. In this case, the history is still in memory. But once you leave the annotation view entirely, the undo/redo history is erased.

**Comment by StoIva** [comment]
ok good to know. that should be in the instructions

**Comment by rsimon** [comment]
Agreed! 👍
