### ISSUE TITLE
Rotate images 

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#61]
this would be a useful feature. rotating them for 360, 90 degrees at a time

**Comment by rsimon** [comment]
Hi @StoIva,

yes, it is possible to implement this as a feature! It's more a question of priority & when to put it on the workplan. Should we discuss at the next meeting?

**Comment by StoIva** [comment]
Yes, i think next meeting would be the right time

**Comment by rsimon** [comment]
Closing this as a duplicate to #70

**Comment by fonziedw** [comment]
Dear Iva and all,
As mentioned earlier please do not add requests for functionality without
discussing this with the entire group, and also not on github.  All new
requests indeed need to be integrated  in the list of priorities we agreed
upon a while ago.
Best,
Hilde
