### ISSUE TITLE
duplicated properties

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#63]
Hi
so this happened. i made just one property, and when i clicked on it the propertz duplicated. and then i deleted one of the duplicated properties in the properties editor and now both properties are gone.
![Screenshot (83)](https://github.com/rsimon/immarkus/assets/128056738/2127f15d-3e37-4541-8afb-cf60bec34de7)

**Comment by rsimon** [comment]
Ah - indeed. It's currently possible to add the same option to an 'Options' filed multiple times! I'm getting the exact same behavior as above. (I'm adding the same option twice. Selecting it renders it twice in the input field, both get checkmarks.) When you delete an option, the list will get filtered by name - which means, yes, all options of that same name will be removed. 

I just published a bugfix. It is now no longer possible to add the same option twice. (Note that any existing data models that already have multiple identical entries will still keep showing them until you delete and re-add.)

**Comment by rsimon** [comment]
For reference: the fix is in this commit https://github.com/rsimon/immarkus/commit/5b82be8a1cae94678ce5d2bebdd30995fc7b3df7
