### ISSUE TITLE
annotation export not showing latest annotations

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#64]
I exported but some newly added annotations were not exported. I think it is because I edited/changed the data model (likely added some properties?), but still the annotations should be shown in a different way?

**Comment by rsimon** [comment]
Hi @StoIva,

which export are you using? The (beta) Excel export will currently only export annotations that have an entity tag. Can you double-check if the missing annotations have an entity tag in the UI?

**Comment by StoIva** [comment]
Hi. asked Sunkyu, it seems that they had an entity type. She changed some properties and that is when the problem occured

**Comment by rsimon** [comment]
I'll need to reproduce this before I can identify what's going wrong. Can you share the following:

- Data model file
- Annotations file for at least one image where annotations are missing in the export
- Info which export you were using (JSON-LD or Excel)

**Comment by StoIva** [comment]
Hi
i requested the files now, sorry for the delays, it's been a bit chaotic

**Comment by rsimon** [comment]
This might possibly the same as issue #87?
