### ISSUE TITLE
Rotate image

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#70]
It would be nice if users could rotate the image; also currently annotations in the selection list is arranged chronologically--I wish I could rearrange/sort my annotations by entities

**Comment by rsimon** [comment]
Is rotation in 90 degree steps sufficient? In this case, this can be nicely handled via two additional buttons (rotate 90 deg clockwise/counterclockwise). I can put that on the list for next week.

**Comment by rsimon** [comment]
P.S. in order to keep the todo list organized I created a new issue with your second request (list sorting) here: #72

**Comment by StoIva** [comment]
i think 90 degree is sufficient, but we can talk about that on the next meeting

**Comment by rsimon** [comment]
Hi @StoIva,

there are now additional options in the annotation list:
- sort by date, descending (= most recent annotation).
- sort by date, ascending (= oldest first).
- sort by the __first__ entity in the annotation (alphabetically).
- filter to show, either, all annotations, or only those tagged with a specific entity class. (Note that this filter is not 'hierarchy aware' at the moment. But could be made so.)

<img width="338" alt="Bildschirmfoto 2024-04-02 um 12 48 56" src="https://github.com/rsimon/immarkus/assets/470971/3ad5761e-1499-430c-b152-38753e8e13dd">

**Comment by rsimon** [comment]
Image rotation is now available: https://github.com/rsimon/immarkus/releases/tag/v0.5.1
