### ISSUE TITLE
Measurment issue

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#75]
Hi
exlanation and json files attached

[雍正_平谷縣志_地里志_城廓屯址圖_p29.json](https://github.com/rsimon/immarkus/files/14756417/_._._._p29.json)
[雍正_平谷縣志_地里志_山川地理圖_p27.json](https://github.com/rsimon/immarkus/files/14756418/_._._._p27.json)
[_immarkus.model.json](https://github.com/rsimon/immarkus/files/14756419/_immarkus.model.json)
[IMMARKUS measurement problem.docx](https://github.com/rsimon/immarkus/files/14756420/IMMARKUS.measurement.problem.docx)

**Comment by rsimon** [comment]
This should now be fixed!

For posterity: (summarized from attached docx):

> When filling in the measurement section you can initially fill in a number value, but once you add a unit, the value field changes to say [object Object].
