### ISSUE TITLE
export data model

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#78]
in the screenshot I appended you can see the data model that is created when you upload the folders to IMMARKUS and make a schema (right), and the other one is the export file from Export-> Data Model. They have the same name but not the same content. The right one includes the metadata schemas. Our suggestion is to simply rename the exported file so it does not create confusion and to point that out in the description (“Your data model in proprietary IMMARKUS JSON format. This file is the same you will find in your work folder as _immarkus.model.json, and is re-published here for convenience”) is incorrect.

let me know what you think
![Screenshot (627)](https://github.com/rsimon/immarkus/assets/128056738/3d53f4c0-2bf8-499c-9ef4-ade87e4c1cbd)

**Comment by rsimon** [comment]
Hi @StoIva, ah - I just checked my code. The export does indeed extract only the Entity Classes, and drops the rest. You are right of course - and the hint text (as well as what I said in the meeting this morning) is wrong. Well, good thing we are revising this part :-)
