### ISSUE TITLE
relations

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#86]
if i have a long list of properties to chose from to create a relation, I cannot see the whole list of properties unless I zoom out of the image a lot. could we have a scrolable menu of properties?

**Comment by rsimon** [comment]
Can you post a screenshot? If you have many properties/relations in the entity schema, the sidebar will scroll - see screenshot.

<img width="1004" alt="Bildschirmfoto 2024-04-16 um 15 06 01" src="https://github.com/rsimon/immarkus/assets/470971/7d6178df-c642-43db-a147-1eceb34d8576">

Or are you referring to the "Options" field type, and the number of option values in the dropdown?

**Comment by StoIva** [comment]
Hi. this is what i meant

![Screenshot (631)](https://github.com/rsimon/immarkus/assets/128056738/6271f599-3474-4210-83fb-49b60c697c49)

**Comment by rsimon** [comment]
Got it, thanks. This should now be fixed!
